apiVersion: v1
kind: ServiceAccount
metadata:
  name: error-backend-sa
  namespace: default  # Ensure the namespace is the same as where your backend is deployed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # You can name this as per your preference, e.g., error-backend-role
  name: error-backend-role
rules:
- apiGroups: [""]
  resources: ["events", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: error-backend-binding
subjects:
- kind: ServiceAccount
  name: error-backend-sa  # Ensure this matches the ServiceAccount name
  namespace: default      # Ensure this matches the namespace where your backend is running
roleRef:
  kind: ClusterRole
  name: error-backend-role  # The ClusterRole you created earlier
  apiGroup: rbac.authorization.k8s.io